# Generated by Django 4.2.6 on 2023-10-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_alter_question_question_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelTable(
            name='answer',
            table='answer',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
